### ISSUE TITLE
怎么运行哦

### ISSUE THREAD

**Issue by jiankian** [ant-design/ant-design-pro-site#100]
我下载到本地，怎么运行？
我先npm install 然后 npm start不会跑。想离线学习下，很多时候在没网的环境

**Comment by afc163** [comment]
请不要在这里回复，如果遇到 pro 的使用问题，建议到 http://github.com/ant-design/ant-design-pro/issues/ 反馈，并学习 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。
