### ISSUE TITLE
ant-design-pro-site，不能部署在windows上吗？

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro-site#102]
如题

**Comment by nikogu** [comment]
请提供更加详细的信息，报错？还是？

**Comment by chenshuai2144** [comment]
windows 不能部署?
![image](https://user-images.githubusercontent.com/8186664/33766474-8d9fd61a-dc58-11e7-93b5-444ac4fbdf7f.png)

**Comment by nikogu** [comment]
@chenshuai2144 这个之前的脚本没有考虑 windows 的情况，要不然你有空改下 script ？有环境应该比较好改，`node ../tool/bin/i` 这样可行？

**Comment by chenshuai2144** [comment]
改 倒是好改,我的解决办法是直接做了个docker.
docker pull 就能解决问题了.
还有 你少写了dva@1.2的依赖

**Comment by waybi** [comment]
@chenshuai2144 docker有具体方案吗

**Comment by chenshuai2144** [comment]
这周应该会上传到docker hub.
到时候@你

**Comment by waybi** [comment]
@chenshuai2144  谢谢

**Comment by chenshuai2144** [comment]
@waybi   根据这个 [Dockerfile](https://github.com/chenshuai2144/ant-design-pro-site/blob/master/Dockerfile) build一下吧...
懒得上传到hub了.
