### ISSUE TITLE
【业务组件】SidePanel 侧栏面板

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro-site#12]
<img width="743" alt="2017-07-21 9 09 53" src="https://user-images.githubusercontent.com/7017767/28445098-b128e3a6-6df4-11e7-8b55-d3d3f9e75098.png">

[交互](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=列表_表格唤起操作)

`设计中`

**Comment by afc163** [comment]
1现在页面中应该都没有用到，这个放缓。

**Comment by chenshuai2144** [comment]
这个是不是 drawer

**Comment by afc163** [comment]
对，可以关了。
