### ISSUE TITLE
Codepen & Riddle link not working

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-site#122]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/507615/32773163-3508b6aa-c963-11e7-8b20-e0fa2533c183.png">

**Comment by nikogu** [comment]
codepen 太反人类了。。。。还是 riddle 好用，搞了半天

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/YErEbN?&editors=001 样式没引入
