### ISSUE TITLE
Both minified css version

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-site#125]
- https://unpkg.com/ant-design-pro@0.2.3-rc.1/dist/ant-design-pro.css 应该是未压缩版本
- https://unpkg.com/ant-design-pro@0.2.3-rc.1/dist/ant-design-pro.min.css

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro-site/commit/8a39604b2e6b2001f455f9ff4ffc00b7c3b2cfc8
