### ISSUE TITLE
编译时出现了以下错误

### ISSUE THREAD

**Issue by apersonw** [ant-design/ant-design-pro-site#132]
ERROR in ./site/theme/template/Home/Page1.jsx
Module not found: Error: Cannot resolve module 'rc-scroll-anim/lib/ScrollOverPAck' in /home/happy/IdeaProjects/ant-design-pro-site/site/theme/template/Home
 @ ./site/theme/template/Home/Page1.jsx 15:22-66

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site/blob/master/package.json#L66

**Comment by apersonw** [comment]
我是git的这个呀，为什么会无法打开呢？
