### ISSUE TITLE
请问index.ejs如何引入assets目录下的js文件？

### ISSUE THREAD

**Issue by zhangzheyuan** [ant-design/ant-design-pro-site#133]
`<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>test</title>
    <link rel="icon" href="https://gw.alipayobjects.com/zos/rmsportal/IOtlElCiWVIOZqgDslYd.png" type="image/x-icon">
</head>
<body>
    <div id="root" style="overflow: hidden;"></div>
    **<script src="/assets/slider.js"></script>**
</body>
</html>
`
上面这样引入slider.js不行

**Comment by afc163** [comment]
请在正确的仓库提问。

**Comment by zhangzheyuan** [comment]
就是正确的仓库，我用ant-design-pro，项目要引入assets中的资源，如何引用

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues
