### ISSUE TITLE
有没有把 ant-design-pro 打包移植到Electron单应用文件的范例？

### ISSUE THREAD

**Issue by anuxs** [ant-design/ant-design-pro-site#139]
理由：
1、有几个业务场景是跨平台的客户端物流业务、销售业务管理程序，客户门店不需要联网，离线操作本地嵌入式数据库，处理结果定期上传；
2、Electron可以匹配跨平台的无需求；
3、ant-design-pro 功能、界面非常匹配预期的UI需求；
4、ant-design-pro如果能够打包成SPA应用，嵌入Electron，完美解决。
5、有没有类似范例？

**Comment by afc163** [comment]
暂时没有，欢迎贡献。
