### ISSUE TITLE
【业务组件】GlobalHeader 全局页头

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro-site#17]
<img width="1160" alt="2017-07-21 5 16 31" src="https://user-images.githubusercontent.com/7017767/28457336-4718d856-6e38-11e7-9066-20b5a052daee.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/44275)

**使用方式**

**功能概要**

- 全局页头框架，有固定的『左（logo）』『中（bars）』『右（消息提醒等内容）』三个区块
- 有默认交互，点击 bars 会触发侧边栏收起/展开
- 有默认样式

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|

**Comment by afc163** [comment]
这块略蛋疼，现在的版本左边 logo 区域是放在 sider 里面的，方便处理折叠。

**Comment by ddcat1115** [comment]
这块毛毛正在做规范，还不能确定 logo 区要不要折叠
