### ISSUE TITLE
"module" entry point contains unsupported syntax 

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design-pro-site#179]
https://github.com/ant-design/ant-design-pro-site/blob/e21f013a808156f3849970b9dffea0ca28325921/config/components/package.config.json#L28
 
The es dir contains es6/7 syntax.

"module" doesn't mean all language features are supported, but actually just indicates that an es2015 module is being exported (See this issue https://github.com/rollup/rollup/issues/969).

This could be resolved either by using lib as the only entry point or compile es dir by babel.

**Comment by chenshuai2144** [comment]
我们换成 rollup 不要用 webpack 好了

**Comment by yesmeck** [comment]
这两个跟这件事没关注
