### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by Mikasa33** [ant-design/ant-design-pro-site#209]
点击超链接跳转地址有误。
https://pro.ant.design/docs/mock-api-cn#%E8%81%94%E8%B0%83

![image](https://user-images.githubusercontent.com/29498153/45086033-d2ed8f80-b134-11e8-860d-578b9710be96.png)

**Comment by chenshuai2144** [comment]
看你提了 pr，帮忙删掉好了

**Comment by Mikasa33** [comment]
已经帮忙删掉超链接了 #211
