### ISSUE TITLE
yarn start 后能访问到doc文件 但访问不了components

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design-pro-site#261]
yarn start 后能访问到doc文件 但访问不了components 如图所示
![image](https://user-images.githubusercontent.com/7939085/54070920-102c0900-42a1-11e9-86d6-1f261a0df28a.png)
![image](https://user-images.githubusercontent.com/7939085/54100562-ffdb7180-43f9-11e9-9b5f-790e506b8a7f.png)
发现是404 不知道是不是windows下路径的问题

**Comment by xiexingen** [comment]
经试验发现在window下components会多了几层，如图 左侧为Linus下 右侧有windows下
![image](https://user-images.githubusercontent.com/7939085/54102222-809e6b80-4402-11e9-93ce-67590dce8b2d.png)
window下没有生成html而且多了scaffold/src/components这个层级

**Comment by chenshuai2144** [comment]
由于 bisheng 的特殊性，可能对 window 支持不是很好，你可以使用 gatsby 分支。它还有一些样式上的问题，但是功能是相同的，对 windows 的支持更加好

**Comment by xiexingen** [comment]
> gatsby

好的 ，谢谢
