### ISSUE TITLE
官网 锚点 bug

### ISSUE THREAD

**Issue by eamonzzz** [ant-design/ant-design-pro-site#274]
点击 右侧的 导航 不会跳转到 相应的 文档节点
![image](https://user-images.githubusercontent.com/20869326/57422830-1bb99300-7244-11e9-9ea5-51c1ae39699b.png)

**Comment by chenshuai2144** [comment]
表现不是很稳定。

**Comment by chenshuai2144** [comment]
gatsby 自带的处理方式有点问题。我关掉了 gatsby 的锚点处理，改用了自己的就好了
