### ISSUE TITLE
https://pro.ant.design 站点无法访问

### ISSUE THREAD

**Issue by huntdream** [ant-design/ant-design-pro-site#275]
<img width="630" alt="Screen Shot 2019-05-10 at 2 34 09 PM" src="https://user-images.githubusercontent.com/7903755/57507269-d921b480-7330-11e9-9f0e-daf261e2c4b6.png">

**Comment by chenshuai2144** [comment]
socket.io的js，怎么会有这个请求，是不是修改了host

![image](https://user-images.githubusercontent.com/8186664/57541274-3180a280-7381-11e9-8e36-0ca65e1f3ad9.png)

**Comment by huntdream** [comment]
没有修改hosts，只挂了一个ss的pac，我用手机Chrome数据流量访问也不行，仍然是白屏。我是点击https://pro.ant.design直接访问的，访问https://pro.ant.design/index-cn是可以的。

**Comment by chenshuai2144** [comment]
我们没有依赖这些文件。 socketio感觉是本地才应该使用的

**Comment by afc163** [comment]
![image](https://user-images.githubusercontent.com/507615/57693010-c681e500-767a-11e9-9b42-abf11fe80c80.png)

**Comment by chenshuai2144** [comment]
发布了新的，再试一下。
我这里被缓存的卡住了。

**Comment by cnhans** [comment]
使用 非dev 打包 发布就知道了，通过带功能的url访问，同样404问题
