### ISSUE TITLE
关于模版集的一个问题

### ISSUE THREAD

**Issue by dawven** [ant-design/ant-design-pro-site#278]
首先，我这边想做一个和ant-design-pro-site一样风格的静态官网。 
 
然后，我在官网了解到landing这个快速生产页面项目工具。我看到例子但都是单叶应用，我想在ant-design-pro-site用landing的话，这两者结合在landing文档那边没有介绍，希望那边也有相关文档。  

还有，ant-design-pro-site这边是用gatsby这个搭建静态网站框架，ant-design系列的官网都是这个搭建的吗，因为我在GitHub项目上只看到pro-site开源了代码库，其他没看见。  

虽然感觉有点超纲，感谢看完。

**Comment by chenshuai2144** [comment]
，ant-design 是 bisheng，我们准备迁移到 antd 但是有一些技术难题

**Comment by ileadall42** [comment]
@chenshuai2144  会考虑抽离出来一个脚手架吗.我看蚂蚁金服系列的官网都不太一致，比如说egg\umi 这样的网站文档都是各用各的0 0，很喜欢ant的风格~

**Comment by afc163** [comment]
antd 网站就是：http://github.com/ant-design/ant-design
