### ISSUE TITLE
【WIP】业务组件及 antd 更新梳理

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro-site#3]
先梳理出来了几个，看看基本方向或者 api 有没问题

> 07.20 有更新

---

##### NoticeIcon 消息图标

<img width="414" alt="2017-07-19 7 50 53" src="https://user-images.githubusercontent.com/7017767/28366199-44a112ee-6cbe-11e7-8868-c7323939e9d7.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/44275)

**使用方式**

	const content = ...
	<NoticeIcon count={7} content={content} />

**功能概要**

- 放在全局导航中，用来提示消息或待办事项等，是对 `Popover` `Icon` `Badge` 的组装
- 有默认 Icon，可配置
- 带 badge（数字和红点两种）
- hover | click | focus 出现弹框
- 通知内容通过 ReactNode 配置，自带『无数据』效果
- 自带『清空』按钮，点击有回调，并呈现『无数据』效果

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| icon       | 展示的 Icon   | ReactNode     | `<Icon type="bell" />`    |
| count      | 消息条数      | number         | -      |
| dot        | 是否带点状 badge   | boolean     | false   |
| trigger    | 触发方式     | Enum{'hover', 'focus', 'click'}     | `hover`   |
| content    | 内容        | ReactNode     | `null`   |
| onClear    | 点击清空的回调        | function     | -   |
| onVisibleChange | 弹框显示隐藏的回调   | (visible) => void | - |

##### GlobalSearch 全局搜索

<img width="642" alt="2017-07-19 7 52 50" src="https://user-images.githubusercontent.com/7017767/28366223-5fe2453c-6cbe-11e7-8073-584310d2cd69.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/44274)

**使用方式**

	const Option = Select.Option;
	<GlobalSearch>
		<Option ...>
		<Option ...>
	</GlobalSearch>

**功能概要**

- 放在全局导航中，触发后展示搜索框，是带定制样式和交互的 `Select`
- 有默认 Icon，可配置
- hover | click | focus 出现搜索框
- 定制样式的搜索框
- 支持带搜索的 Select（单选） 相关功能 [Select](https://ant.design/components/select-cn/)
- 子元素为 Select.Option

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| icon       | 展示的 Icon   | ReactNode     | `<Icon type="search" />`   |
| trigger    | 触发方式     | Enum{'hover', 'focus', 'click'}     | `hover`   |

##### FooterToolbar 底部工具栏

<img width="1028" alt="2017-07-19 7 53 55" src="https://user-images.githubusercontent.com/7017767/28366238-6f72dffc-6cbe-11e7-8bfe-40533de6381c.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/51658)

**使用方式**

	<FooterToolbar>
		...content...
	</FooterToolbar>

**功能概要**

- 静态容器，相对于页面固定在底部，但宽度与父元素相同

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| style       | 样式   | object     | -    |

##### PageHeader

<img width="935" alt="2017-07-19 7 55 07" src="https://user-images.githubusercontent.com/7017767/28366258-835b71c8-6cbe-11e7-9530-b69006440a2b.png">

[视觉稿](https://lark.alipay.com/ui-assets/leu0s4/54196)
[交互说明](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=页头)

**使用方式**

	<PageHeader>
		content
	</PageHeader>
	
**功能概要**

- 静态容器，包含页头部分的固定结构 ↓

<img width="427" alt="2017-07-19 8 18 42" src="https://user-images.githubusercontent.com/7017767/28366511-a0f2cbea-6cbf-11e7-9a31-bfcc90f347a4.png">

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| nav        | 顶部区域，建议放置面包屑等导航   | ReactNode     | -    |
| logo       | logo区域，也可用来放返回按钮   | ReactNode     | -    |
| title       | title 区域   | ReactNode     | -    |
| action       | 操作区，位于 title 行的行尾   | ReactNode     | -    |
| extraContent`？`       | 页头底部的额外内容，建议放页内导航  | ReactNode     | -    |

##### Footer

<img width="903" alt="2017-07-20 2 59 10" src="https://user-images.githubusercontent.com/7017767/28406632-ee8c136c-6d63-11e7-9fc0-6cfbdb33ee0a.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/44366)

**使用方式**

	<Footer>
		...content...
	</Footer>

**功能概要**

- 静态容器，会对内容的颜色，大小，对齐方式等进行定制

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| style       | 样式   | object     | -    |

##### ExceptionPage

<img width="1081" alt="2017-07-20 3 18 53" src="https://user-images.githubusercontent.com/7017767/28406708-32565576-6d64-11e7-9b2f-8b1dba87bfd9.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa#6388)

**使用方式**
	const link = <Button>Home</Button>
	<ExceptionPage type="404" />
	<ExceptionPage title="出错啦！" desc="我也不知道为啥" img="img.png" extra={link} />

**功能概要**

- 异常页面，默认支持 404，500 等场景，每个场景有默认图片，title，描述，可修改

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| type       | 页面类型，若配置，则自带配套的 title，desc，img     | Enum{'404', '500', '503'}  | -    |
| title       | 标题     | ReactNode  | -    |
| desc       | 说明     | ReactNode  | -    |
| img       | 图片地址     | string  | -    |
| extra       | 额外内容，推荐放置跳转链接    | ReactNode  | -    |

##### ResultPage

<img width="669" alt="2017-07-20 3 41 29" src="https://user-images.githubusercontent.com/7017767/28406853-a67d38de-6d64-11e7-9017-88eb64e61ae5.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/45574)

**使用方式**
	const link = <Button>Home</Button>
	<ResultPage type="success" title="申请成功" desc="运气真好！" extra={link} />
	
**功能概要**

- 结果页面，支持 成功，警告，失败 三种场景，每个场景有默认顶部 Icon
**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| type       | 页面类型     | Enum{'success', 'warning', 'error'}  | -    |
| title       | 标题     | ReactNode  | -    |
| desc       | 说明     | ReactNode  | -    |
| extra       | 额外内容，推荐放置跳转链接等    | ReactNode  | -    |

##### Card

- 样式调整
- 增加『Title 部分带 Tabs』的示例 [视觉](https://lark.alipay.com/ui-assets/bf3zoa/51515)

##### Tabs

- 支持 tab bar 居中展示 [视觉](https://lark.alipay.com/ui-assets/bf3zoa/45524)
- 支持页签和内容分开渲染？[视觉](https://lark.alipay.com/ui-assets/bf3zoa/50773)
- 样式调整
- 增加『有顺序的页签』示例 [案例(见此 demo -页内导航)](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=页头)

##### Input

- Input.Group `compact` 模式支持输入框及按钮的组合 [案例-主搜索](https://lark.alipay.com/ui-assets/bf3zoa/44455)

##### List 列表 （新增）

- [交互说明](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=列表-纵向布局)

##### Divider 分割线 （新增）

[视觉稿，暂定](https://designlab.alipay.com/template/preview/59663dd8074b5a2c09907853)

**使用方式**

	<Divider size="small" />
	
**功能概要**

- 自带样式的分割线，根据设计，目前有两种 size

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| size       | 大小（边距不同）   | Enum{'small', 'default'}     | `default`    | 
| style       | 样式   | object     | -    |

**Comment by afc163** [comment]
Divider 放到 antd。

**Comment by ddcat1115** [comment]
已调整

**Comment by afc163** [comment]
Card 要增加 actions 和 cover 的相关配置。

**Comment by afc163** [comment]
Tabs 的 card 样式要进行改造（顶部蓝条的方式）。

**Comment by nikogu** [comment]
我觉得要不之后的业务组件，每个单独一个 issue 说明 api 以及相关，这样以后的文档基本上就直接 copy 过去就可以了

**Comment by afc163** [comment]
这样好，分开也比较好回复和关闭。@ddcat1115

**Comment by ddcat1115** [comment]
好的，我拆一下

**Comment by ddcat1115** [comment]
## 0720 确认的 业务组件/组件/demo 内容

> 目前的视觉稿以页面为维度，后续设计师会针对业务组件梳理规则，单独拎出来指定视觉规范，目前已完成的有：PageHeader ，其他的均有可能在目前视觉稿上有少量改动。

> antd 优化/新增 这部分，确定后会挪到 antd issue 中。

#### 业务组件

- NoticeIcon 消息图标 [#5](https://github.com/ant-design/test/issues/5)
- GlobalSearch 全局搜索 [#6](https://github.com/ant-design/test/issues/6)
- FooterToolbar 底部工具栏 [#7](https://github.com/ant-design/test/issues/7)
- PageHeader 页头 [#8](https://github.com/ant-design/test/issues/8)
- Footer 页脚 [#9](https://github.com/ant-design/test/issues/9)
- ExceptionPage 异常页面 [#10](https://github.com/ant-design/test/issues/10)
- ResultPage 处理结果页面 [#11](https://github.com/ant-design/test/issues/11)
- SidePanel 侧栏面板 [#12](https://github.com/ant-design/test/issues/12)
- MiniChartCard 迷你图表卡片 [#13](https://github.com/ant-design/test/issues/13)
- InfoGroup 信息组 [#14](https://github.com/ant-design/test/issues/14)

#### antd 优化/新增

- Card
	- 增加『Title 部分带 Tabs』的示例 [视觉](https://lark.alipay.com/ui-assets/bf3zoa/51515)
	- 增加灰底 title 区域样式 [视觉](https://lark.alipay.com/ui-assets/bf3zoa/50773)

- Tabs
	- 支持 tab bar 居中展示 [视觉](https://lark.alipay.com/ui-assets/bf3zoa/45524)
	- 支持页签和内容分开渲染？[视觉](https://lark.alipay.com/ui-assets/bf3zoa/50773)
	- 增加火柴棍在上方的样式
	- 增加『有顺序的页签』示例 [案例(见此 demo -页内导航)](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=页头)

- Input
	- Input.Group `compact` 模式支持输入框及按钮的组合 [案例-主搜索](https://lark.alipay.com/ui-assets/bf3zoa/44455)

- Form
	- 新增报错模式 [视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/45521)
	- 新增动态展示表单控件的示例 [交互-响应式增加内容](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=组合表单)

- List 列表 （新增）
	-  [交互说明1](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=列表-纵向布局)
	-  [交互说明2](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=列表-网格布局) `感觉更像卡片，待讨论`
	-  [交互说明3](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=列表_表格唤起操作)

- Divider 分割线 （新增）
	-  [视觉稿](https://designlab.alipay.com/template/preview/59663dd8074b5a2c09907853)

#### 模块/片段

- 实时搜索 [交互](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=搜索和筛选)
- 页签组合表格 [交互](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=组合表格)
- 纵向分布的表单 [交互](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=组合表格)

**Comment by afc163** [comment]
@afc163 @nikogu 都去 Review 一下业务组件范畴和 API，今天下班前完成。

**Comment by afc163** [comment]
缺少主搜索。

**Comment by ddcat1115** [comment]
打算这样来支持

<img width="581" alt="2017-07-21 4 05 07" src="https://user-images.githubusercontent.com/7017767/28454819-3aa7397c-6e2f-11e7-853c-77f5e29fb51b.png">

**Comment by afc163** [comment]
那其实就没必要做了，看看设计师那么要不要丰富一下主搜索的交互。

**Comment by ddcat1115** [comment]
只是没必要单独做一个主搜索组件，Input.Group 还是要改造才能支持按钮吧。我再跟海纳确认下

**Comment by ddcat1115** [comment]
主搜索还在设计中，暂时不单独拎出来

**Comment by afc163** [comment]
@ddcat1115 可以先把坑挖出来。

**Comment by afc163** [comment]
Login 应该也做成组件。

**Comment by afc163** [comment]
倒计时也抽成组件吧。

**Comment by afc163** [comment]
@ddcat1115 业务组件一期可以收一下了，把现有完成度满分的组件列出来看看，发布一个 alpha 版本试试。

**Comment by afc163** [comment]
- [ ] 图表组件的 API 文档里很多默认值是错的，需要修正一下。
