### ISSUE TITLE
v4 动态菜单 具体怎么加载的？求完整版教程。

### ISSUE THREAD

**Issue by lralin** [ant-design/ant-design-pro-site#304]
完全没看懂文档里面的动态菜单啊。[从服务器请求菜单](https://pro.ant.design/docs/router-and-nav-cn#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95)
state = {
  menuData: [],
};

componentDidMount() {
  fetch('/api/example.json')
    .then(response => response.json())
    .then(data => {
      this.setState({
        menuData: data,
      });
    });
}

...

menuDataRender={() => this.state.menuData || []}
这三个方法具体要放在哪里？在BasicLayout.tsx里面完全就是报错啊。

**Comment by lralin** [comment]
[参考](https://github.com/ant-design/ant-design-pro/issues/4358)这个issues写出来了。注意的细节比较多。

**Comment by zhangxinxing59** [comment]
config里面还需要写路由吗？不写的话好像运行不了。从后台拉取的路由跟config里面配置的路由有什么关系？

**Comment by liuyanming9551** [comment]
@lralin 请问你试过这个方案吗？为什么我按着这个方案走，还是加载的config里面的菜单呢？我是自己写了一个mock数据

**Comment by DWAO** [comment]
> @lralin 请问你试过这个方案吗？为什么我按着这个方案走，还是加载的config里面的菜单呢？我是自己写了一个mock数据

修改BasicLayout 中的  menuDataRender={() => menuData} 就可以显示 了

**Comment by ms20hj** [comment]
/**
 * use Authorized check all menu item
 */
const menuDataRender = menuList =>
  menuList.map(item => {
    const localItem = { ...item, children: item.children ? menuDataRender(item.children) : [] };
    return Authorized.check(item.authority, localItem, null);
  });

const footerRender = (_, defaultDom) => {
  if (!isAntDesignPro()) {
    return defaultDom;
  }

  return (
    <>
      {defaultDom}
      <div
        style={{
          padding: '0px 24px 24px',
          textAlign: 'center',
        }}
      >
        <a href="https://www.netlify.com" target="_blank" rel="noopener noreferrer">
          <img
            src="https://www.netlify.com/img/global/badges/netlify-color-bg.svg"
            width="82px"
            alt="netlify logo"
          />
        </a>
      </div>
    </>
  );
};

const BasicLayout = props => {
  const { dispatch, children, settings } = props;
  const [menuData, setMenuData] = useState([]);

  useEffect(() => {
    if (dispatch) {
      dispatch({
        type: 'global/fetchRoutes',
      }).then(() => {
        const { routes } = props;
        setMenuData(routes || []);
      });
    }
  }, []);

  const handleMenuCollapse = payload => {
    if (dispatch) {
      dispatch({
        type: 'global/changeLayoutCollapsed',
        payload,
      });
    }
  };

  return (
    <ProLayout
      logo={logo}
      onCollapse={handleMenuCollapse}
      menuItemRender={(menuItemProps, defaultDom) => {
        if (menuItemProps.isUrl) {
          return defaultDom;
        }

        return <Link to={menuItemProps.path}>{defaultDom}</Link>;
      }}
      breadcrumbRender={(routers = []) => [
        {
          path: '/',
          breadcrumbName: formatMessage({
            id: 'menu.home',
            defaultMessage: 'Home',
          }),
        },
        ...routers,
      ]}
      itemRender={(route, params, routes, paths) => {
        const first = routes.indexOf(route) === 0;
        return first ? (
          <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
        ) : (
          <span>{route.breadcrumbName}</span>
        );
      }}
      footerRender={footerRender}
      menuDataRender={() => menuData}
      formatMessage={formatMessage}
      rightContentRender={rightProps => <RightContent {...rightProps} />}
      {...props}
      {...settings}
    >
      {children}
    </ProLayout>
  );
};

export default connect(({ global, settings }) => ({
  collapsed: global.collapsed,
  settings,
  routes: global.routes,
}))(BasicLayout);



global/fetchRoutes 对应后端的返回值如下图所示：
![image](https://user-images.githubusercontent.com/23376892/72241312-72703b80-3621-11ea-9455-51107923b05a.png)
。
不知道为什么菜单有时候能正常显示有时候就显示不出来。

而且f5刷新一下，原先存在的菜单也没了，但是通过network可以看到去后端请求了接口，数据也正常返回，就是页面上没有重新渲染

**Comment by elangren123** [comment]
完整实现:
这个实现参考了网上多位大侠的方案，最终融合而成。大致分为如下六步。

第一步，添加model
在src/models/中添加menu.ts文件，文件内容：
`import { getMenuData } from '@/services/menu'; // 通过后台返回特定的数组json或者mock模拟数据
import { Reducer } from 'redux';
import { Effect } from './connect';

export interface MenuModelState {
  menuData: any[];
}

export interface MenuModelType {
  namespace: 'menu';
  state: MenuModelState;
  effects: {
    getMenuData: Effect;
  };
  reducers: {
    save: Reducer<MenuModelState>;
  };
}

const MenuModel: MenuModelType = {
  namespace: 'menu',
  state: {
    menuData: [],
  },
  effects: {
    *getMenuData({ payload, callback }, { call, put }) {
      const response = yield call(getMenuData);
      yield put({
        type: 'save',
        payload: response,
      });
      if (callback) callback(response);
    },
  },

  reducers: {
    save(state, action) {
      return {
        ...state,
        menuData: action.payload || [],
      };
    },
  },
};
export default MenuModel;`

第二步，添加service
在src/services/中添加menu.ts文件，文件内容：
`import request from 'umi-request';
const BASE_URL = '/v1';


export async function getMenuData(params:any) {
  console.log('===========in getMenuData');
  console.log(params);
  return request(BASE_URL + '/menu/getMenuData', {
    method: 'GET',
    params: params,
  });
}`

第三步，修改connect.d.ts的ConnectState来添加menu
修改文件src/models/connect.d.ts：
![image](https://user-images.githubusercontent.com/63434063/79522843-5dc39980-808f-11ea-9c38-3d9a65642247.png)

第四步，修改BasicLayout.tsx文件来关联menu
修改文件src/layouts/BasicLayout.tsx：
![image](https://user-images.githubusercontent.com/63434063/79522936-95cadc80-808f-11ea-800a-27aa3640ea68.png)

第五步，添加mock文件
在src/mock/中添加menu.ts文件，文件内容：
`export default {
    'Get /v1/menu/getMenuData': [
        {
          path: '/dashboard',
          name: 'dashboard',
          icon: 'dashboard',
          children: [
            {
              path: '/dashboard/analysis',
              name: 'analysis',
              exact: true,
            },
            {
              path: '/dashboard/monitor',
              name: 'monitor',
              exact: true,
            },
            {
              path: '/dashboard/workplace',
              name: 'workplace',
              exact: true,
            },
          ],
        }
      ],
};`

第六步，支持国际化
为了menu支持国际化，只需要在menu数据中添加locale属性。
修改src/mock/menu.ts：

`export default {
    'Get /v1/menu/getMenuData': [
        {
          path: '/dashboard',
          name: 'dashboard',
          locale: 'menu.dashboard',//国际化
          icon: 'dashboard',
          children: [
            {
              path: '/dashboard/analysis',
              name: 'analysis',
              exact: true,
            },
            {
              path: '/dashboard/monitor',
              name: 'monitor',
              exact: true,
            },
            {
              path: '/dashboard/workplace',
              name: 'workplace',
              exact: true,
            },
          ],
        }
      ],
};`

同时在src/locales/xxx/menu.ts中添加相应的国际化配置。比如：
src/locales/zh-CN/menu.ts中配置menu.dashboard：
`export default {
  ...
  'menu.dashboard': '桌面'
  }`

到此为止，你的前端已经支持了动态Menu了，并且实现了通过mock的方式来调试了。后面，你需要在服务端实现接口Get /v1/menu/getMenuData就可以了。

**Comment by aoyinke** [comment]
> 完整实现:
> 这个实现参考了网上多位大侠的方案，最终融合而成。大致分为如下六步。
> 
> 第一步，添加model
> 在src/models/中添加menu.ts文件，文件内容：
> `import { getMenuData } from '@/services/menu'; // 通过后台返回特定的数组json或者mock模拟数据
> import { Reducer } from 'redux';
> import { Effect } from './connect';
> 
> export interface MenuModelState {
> menuData: any[];
> }
> 
> export interface MenuModelType {
> namespace: 'menu';
> state: MenuModelState;
> effects: {
> getMenuData: Effect;
> };
> reducers: {
> save: Reducer;
> };
> }
> 
> const MenuModel: MenuModelType = {
> namespace: 'menu',
> state: {
> menuData: [],
> },
> effects: {
> *getMenuData({ payload, callback }, { call, put }) {
> const response = yield call(getMenuData);
> yield put({
> type: 'save',
> payload: response,
> });
> if (callback) callback(response);
> },
> },
> 
> reducers: {
> save(state, action) {
> return {
> ...state,
> menuData: action.payload || [],
> };
> },
> },
> };
> export default MenuModel;`
> 
> 第二步，添加service
> 在src/services/中添加menu.ts文件，文件内容：
> `import request from 'umi-request';
> const BASE_URL = '/v1';
> 
> export async function getMenuData(params:any) {
> console.log('===========in getMenuData');
> console.log(params);
> return request(BASE_URL + '/menu/getMenuData', {
> method: 'GET',
> params: params,
> });
> }`
> 
> 第三步，修改connect.d.ts的ConnectState来添加menu
> 修改文件src/models/connect.d.ts：
> ![image](https://user-images.githubusercontent.com/63434063/79522843-5dc39980-808f-11ea-9c38-3d9a65642247.png)
> 
> 第四步，修改BasicLayout.tsx文件来关联menu
> 修改文件src/layouts/BasicLayout.tsx：
> ![image](https://user-images.githubusercontent.com/63434063/79522936-95cadc80-808f-11ea-800a-27aa3640ea68.png)
> 
> 第五步，添加mock文件
> 在src/mock/中添加menu.ts文件，文件内容：
> `export default { 'Get /v1/menu/getMenuData': [ { path: '/dashboard', name: 'dashboard', icon: 'dashboard', children: [ { path: '/dashboard/analysis', name: 'analysis', exact: true, }, { path: '/dashboard/monitor', name: 'monitor', exact: true, }, { path: '/dashboard/workplace', name: 'workplace', exact: true, }, ], } ], };`
> 
> 第六步，支持国际化
> 为了menu支持国际化，只需要在menu数据中添加locale属性。
> 修改src/mock/menu.ts：
> 
> `export default { 'Get /v1/menu/getMenuData': [ { path: '/dashboard', name: 'dashboard', locale: 'menu.dashboard',//国际化 icon: 'dashboard', children: [ { path: '/dashboard/analysis', name: 'analysis', exact: true, }, { path: '/dashboard/monitor', name: 'monitor', exact: true, }, { path: '/dashboard/workplace', name: 'workplace', exact: true, }, ], } ], };`
> 
> 同时在src/locales/xxx/menu.ts中添加相应的国际化配置。比如：
> src/locales/zh-CN/menu.ts中配置menu.dashboard：
> `export default { ... 'menu.dashboard': '桌面' }`
> 
> 到此为止，你的前端已经支持了动态Menu了，并且实现了通过mock的方式来调试了。后面，你需要在服务端实现接口Get /v1/menu/getMenuData就可以了。

这样做的确可以实现动态菜单，但是好像没办法加component属性，也就是虽然左侧菜单栏动态变化了，但是对应的组件没有加载出来。。
