### ISSUE TITLE
您好 我想修改一下本软件 需要有什么注意的地方吗

### ISSUE THREAD

**Issue by wangyi7099** [ant-design/ant-design-pro-site#308]
比如在协议里面 我可以改成自己的名字吗
我想把它改成一个基于gatsby的一个主题，然后类似于[vuepress](https://github.com/vuejs/vuepress)可配置的。

**Comment by wangyi7099** [comment]
@afc163  大佬求看~~~

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site/blob/master/LICENSE

**Comment by ileadall42** [comment]
很期待你可以改成一个主题啊！！最好再把landing page 的相关模块集成一下，弄成可配置，然后如果再有个cms的管理那真的完美！

**Comment by wangyi7099** [comment]
好的 就是说那个license必须原封不动是吧？

**Comment by xiaohuoni** [comment]
@wangyi7099 协议是指MIT，你可以随意修改。最好著名出处，当然你不想著名也可以。MIT你爱怎么弄都可以（微笑）

**Comment by wangyi7099** [comment]
好的 我知道了 谢谢

**Comment by afc163** [comment]
MIT 有义务的：https://zh.wikipedia.org/wiki/MIT%E8%A8%B1%E5%8F%AF%E8%AD%89

**Comment by wangyi7099** [comment]
好的 我知道了 可不可以这样 我参考了一下 
[ant-design-vue](https://github.com/vueComponent/ant-design-vue/blob/master/LICENSE)的license，上面是自己的，下面是原软件的
