### ISSUE TITLE
mock 方案讨论

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-pro-site#33]
1. 使用 roadhog 标准解决方案（本地 server） `现在的方式`
    - 问题：站点演示不方便，需要额外做处理
2. 使用第三方站点，如：http://mocky.io/
    - 问题：逻辑处理太弱，数据单独在网站上跟本身项目分离
3. 使用本地化方案，如：https://github.com/Houfeng/faked
    - 问题：感觉跟现阶段标准不符合，有点 `山寨` 的感觉

建议：还是采用 roadhog 的标准方案，不过本地静态化处理可以参看 `facked` 的方式，封装一个函数作为静态化处理。

@ddcat1115 @afc163 看看

**Comment by afc163** [comment]
在 http://now.sh/ 上单独部署一个 mock 数据服务如何？

**Comment by afc163** [comment]
roadhog 的默认 mock 方案是比较简陋的。如果单独搞一个类似 https://github.com/smollweide/node-mock-server 的方案，还可以有页面展示 API。这样我这个 https://github.com/ant-design/test/tree/doc-api-generator 里的 api blueprint 的方案就可以放弃了。

**Comment by nikogu** [comment]
我觉得可行，我看看啊

**Comment by afc163** [comment]
https://www.easy-mock.com/

**Comment by afc163** [comment]
> 如果我们使用单独部署的服务是还不错，但是可能业务或者用户来用的时候没本地 mock 那么方便 ＝。-

还是本地 mock 方案，只是试试换一个服务而已。

**Comment by nikogu** [comment]
最好是本地写 api doc，自动生成 mock，现在有这种工具吗，没的话等模板写完可以搞一个 🐵

**Comment by afc163** [comment]
我也找过，做的最好的是 https://swagger.io/ 和 http://apiblueprint.org/ 相关的工具，但是特别满意的没有。

**Comment by afc163** [comment]
有没有可能把 mock 接口都读取到一个文档页面上能统一查看。

**Comment by nikogu** [comment]
我觉得可以，我抽空试试

**Comment by nikogu** [comment]
```
const proxy = {
  /**
    {
       params: {
          id: '需要的id参数'
       },
       return: {
         name: '名称', 
         avatar: '头像',
       },
    }
  */
  'GET /api/currentUser': {
    name: 'momo.zxy',
    avatar: imgMap.user,
    userid: '00000001',
    notifyCount: 5,
  },
  'GET /api/project/notice': getNotice,
  'GET /api/activities': getActivities,
  'GET /api/rule': getRule,
  /**
    {
       params: {
          pageSize: '分页'
       },
       return: {
         success: '是否成功', 
         data: [{
           name: 'xxxx',
           total: 'xxxxx'.
         }],
       },
    }
  */
  'POST /api/rule': postRule,
};
```

这样用 `json` 定义出输入输出如何（感觉有点山寨，不过读取实现容易的多了），然后读取这个文件，自动生成一个页面（类似现在的组件 API 文档的样式）作为 `api doc`

**Comment by afc163** [comment]
这样写起来也蛮累的，而且和真实数据不同步，后面会懒得改。

我的想法是不用文档方式来列出具体参数。给出：

- 有哪些接口。
- GET的接口给个链接点过去看看有啥返回。
- POST PUT DELETE 在本地调试/构建版本时可以给个按钮，点击触发请求发送。

**Comment by nikogu** [comment]
我觉得 ok，抽空先搞个，然后后面再改改

**Comment by nikogu** [comment]
刚才尝试写了下，遇到了些问题大家讨论下：

#### 关于请求参数
请求参数如果不显示的指明，是根本不知道可以传什么参数的，所以打算需要说明参数的，mock 写法如下：
```
'GET /api/currentUser': {
      $params: {
          id: {
            description: '用户 id',// 接口参数说明
            exp: '1', // 样例值
          }
      },
      $body: {
        name: 'momo.zxy',
        avatar: imgMap.user,
        userid: '00000001',
        notifyCount: 5,
      },
  },
```

不需要额外说明的跟之前的 mock 保持一致：
```
'GET /api/currentUser': {
  name: 'momo.zxy',
  avatar: imgMap.user,
  userid: '00000001',
  notifyCount: 5,
},
```

#### 关于静态化
因为我们未来部署的时候都是静态站点（没有服务的），所以 mock 现在的处理就是静态化：其实就是build 的时候改了 request，然后返回 mock 的函数，相当于完全没有走网络请求，都是直接访问的对象和方法。

现在想直接通过 mock 文件（.roadhog.mock.js）生成 api 的展示是可以做到的，但是部署以后依旧是静态，所以打算：当我点一个请求如 `/api/user`，就弹出一个 Modal ，里面是格式化后的 json 数据，是否可行？

从功能上来讲，确实可以展示出脚手架所有的请求接口，定义的参数以及返回的结果，但是就是不是走的网络请求。这样其实在我们的脚手架上新建一个 router ApiDoc，然后获取 `.roadhog.mock.js` 的 mock 数据，进行处理展示即可。

@afc163 @ddcat1115 看下，是否可行

**Comment by afc163** [comment]
> 当我点一个请求如 /api/user，就弹出一个 Modal ，里面是格式化后的 json 数据，是否可行？

这样挺好的。

> 从功能上来讲，确实可以展示出脚手架所有的请求接口，定义的参数以及返回的结果，但是就是不是走的网络请求。

本地起服务时做网络请求，构建后展示静态的结构就好。

> .roadhog.mock.js

如果我们做了封装，可能需要叫一个新名字，以免用户去 roadhog 查文档时发现对不上。

**Comment by nikogu** [comment]
> 如果我们做了封装，可能需要叫一个新名字，以免用户去 roadhog 查文档时发现对不上。

这个要不然用注释好了，这样话，一般用户不需要 apidoc 的，他直接去掉 $params 就可以用了，如果新建一个文件，会不会增加用户的理解成本。其它的写法都跟原来的一模一样。

**Comment by afc163** [comment]
我当心用户把 $params 和 $body 的用法直接用到 roadhog 的项目里，就直接挂了。

毕竟他会觉得都是 `.roadhog.mock.js`，为啥不一样。

**Comment by nikogu** [comment]
https://github.com/nikogu/roadhog-api-doc

**Comment by nikogu** [comment]
![proxy](https://user-images.githubusercontent.com/1179603/29620299-1c1acb78-8850-11e7-99dd-c30a8beb4369.gif)

https://github.com/nikogu/roadhog-api-doc

### todo

- [ ] 样式体验优化
- [ ] 支持 build，（期望在 dist 目录生成 `api.html`, `api.js`, `api.css` 三个文件）
- [ ] 增强 roadhog mock 功能（如：提供静态处理函数工具等）

**Comment by afc163** [comment]
赞赞赞！

**Comment by nikogu** [comment]
![image](https://user-images.githubusercontent.com/1179603/29659001-6f24aa60-88ef-11e7-99b6-122b75058f3f.png)

优化了一下样式，build 也基本可用，不过遇到一个问题，直接运行 
`./node_module/.bin/roadhog-api-doc start` 是可以的，但是把它写到 `npm script`，如: `"doc": "roadhog-api-doc start"`，然后 `tnpm run doc`，就挂了。。。不知道为什么，报错也是依赖的错误，但是其实应该是一样的场景才对，百思不得其解 😢

**Comment by afc163** [comment]
报了什么错？

**Comment by nikogu** [comment]
> 报了什么错？

```
Starting the development server...

Failed to compile.

../node_modules/_react-dev-utils@2.0.1@react-dev-utils/ansiHTML.js
Module not found: Can't resolve 'anser' in '/Applications/MAMP/htdocs/www/alipay-cd/project/antd-pro/antd-pro/scaffold/node_modules/_react-dev-utils@2.0.1@react-dev-utils'

Compiling...
Failed to compile.
```

**Comment by afc163** [comment]
发现 https://www.getpostman.com/ 好强大啊。

**Comment by afc163** [comment]
看看能否一键生成 API 标准格式文件，导入进去：

<img width="560" alt="image" src="https://user-images.githubusercontent.com/507615/30276638-12df3fb6-9738-11e7-91dc-96b00527ddda.png">
