### ISSUE TITLE
Development manual

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-site#55]
- https://ng-admin-book.marmelab.com/
- https://akveo.github.io/ng2-admin/articles/001-getting-started/
- https://adminlte.io/docs/2.4/installation
- https://github.com/facebookincubator/create-react-app
- 全栈指引平台

**Comment by afc163** [comment]
- [ ] 上手 Getting Started
- [ ] 目录结构
- [ ] 布局
- [ ] 路由和菜单
- [ ] 开发业务组件
- [ ] 新增页面
- [ ] 和服务端进行交互
- [ ] 样式
- [ ] Mock 和联调
- [ ] 构建和发布
- [ ] 国际化
- [ ] 修改主题
- [ ] UI 测试
- [ ] FAQ
- [ ] 更新日志

**Comment by nikogu** [comment]
感觉差不多，可以增加一个『使用图表』？然后推荐用 g2...

**Comment by afc163** [comment]
已添加。为啥我们不用 https://github.com/antvis/g2-react ？

**Comment by nikogu** [comment]
@afc163 这个之前跟图形组的多位同学沟通过了，都一致建议直接使用 g2 ，原因如下：
1. 这个 g2-react 并不是图形组同学维护，后续升级排查错误有一定维护成本；
2. g2 是命令式语法，用 react 包装以后还是一样的写法，并没有不同；
3. 距之前使用过的部分开发同学反馈，有一定的坑，大部分业务线的都直接用的 g2；

**Comment by afc163** [comment]
👌，之后 pro 的可视化图表就是 React 里用 G2 的最佳实践了。

**Comment by nikogu** [comment]
好的，我之后再让图形组的同学帮忙 review 下代码，优化下

**Comment by ddcat1115** [comment]
#47  这个还要不要加进去？

**Comment by afc163** [comment]
加了，我们分下工，https://github.com/ant-design/test/issues/48 搞完后就开始写。

**Comment by afc163** [comment]
@ddcat1115 先去参照 https://ant.design/docs/spec/introduce-cn 这个页面的结构把文档坑位挖出来吧。

**Comment by afc163** [comment]
简单分了一下工，下周开始写文档！

**Comment by afc163** [comment]
感觉文档有点多，应该分个类。

**Comment by ddcat1115** [comment]
要不要把开发流程必不可少的拎出来属于一个类目，剩下的零散的另外一个，或者散放？

**Comment by afc163** [comment]
15 号之前要写一个初稿出来。@ddcat1115 @nikogu

**Comment by nikogu** [comment]
好的 :1st_place_medal:

**Comment by ddcat1115** [comment]
收到

**Comment by nikogu** [comment]
本周开始写文档啦！！ 📝 📝 📝 📝 📝 📝 📝 📝 📝 📝 📝 📝 📝 📝 📝 📝

**Comment by afc163** [comment]
分了一下类。写的时候尽量从后端同学的角度和知识深度来写。

**Comment by afc163** [comment]
部分可以参考：https://github.com/zuiidea/antd-admin#faq

**Comment by nikogu** [comment]
『路由和菜单 @ddcat1115』 和 『和服务端进行交互 @nikogu』 由于 @ddcat1115 在搞 router，交换一下

**Comment by afc163** [comment]
现在本地 http://127.0.0.1:8001/docs/getting-started 可以看文档效果了。

有几个问题统一改改：

- [ ] 代码缩进，统一两个空格。
- [ ] 图片，不用左右布局，统一顺排即可。
- [ ] 截图都有点大，需要固定下宽度保证清晰度。
- [ ] 注意中英文空格和标点符号。

**Comment by afc163** [comment]
- [ ] 可以针对代码块加一些截图，比如可视化这里，加个这段代码对应的图表样式，会更有可读性。

<img width="670" alt="image" src="https://user-images.githubusercontent.com/507615/30579293-9ab0d8e2-9d4a-11e7-9237-dc214cbf68ce.png">

**Comment by afc163** [comment]
### 发布和部署

- [ ] 关键命令要单独列出来，这样比较醒目。

```bash
$ npm run build
```

**Comment by nikogu** [comment]
> 发布部署

https://github.com/ant-design/test/commit/0c0d9afc795ce4d29b0bda8809101dd63a45293f
