### ISSUE TITLE
【业务组件】GlobalSearch 全局搜索

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro-site#6]
<img width="642" alt="2017-07-19 7 52 50" src="https://user-images.githubusercontent.com/7017767/28366223-5fe2453c-6cbe-11e7-8073-584310d2cd69.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/44274)
[交互](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=侧边导航)

**使用方式**

	const Option = Select.Option;
	<GlobalSearch>
		<Option ...>
		<Option ...>
	</GlobalSearch>

**功能概要**

- 放在全局导航中，触发后展示搜索框，是带定制样式和交互的 `Select`
- 有默认 Icon，可配置
- hover | click | focus 出现搜索框
- 定制样式的搜索框
- 支持带搜索的 Select（单选） 相关功能 [Select](https://ant.design/components/select-cn/)
- 子元素为 Select.Option

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| icon       | 展示的 Icon   | ReactNode     | `<Icon type="search" />`   |
| trigger    | 触发方式     | Enum{'hover', 'focus', 'click'}     | `hover`   |

**Comment by nikogu** [comment]
感觉还需要一个 `theme`，因为那个字体颜色和 border 以及 icon 可能需要两套（黑 & 白）

**Comment by afc163** [comment]
不要用 Option，直接接收一个 `data={{ ... }}` 的数据属性。

**Comment by ddcat1115** [comment]
@nikogu  这个搜索只会放导航里，目前好像只有蓝色一种，后续设计师梳理之后再看需要加不

**Comment by ddcat1115** [comment]
@afc163 可能需要表达 OptGroup，disabled 之类的，感觉数据结构有点复杂

**Comment by afc163** [comment]
主要因为数据是动态从后台读取的，data 可能反而方便点。

**Comment by ddcat1115** [comment]
后台给的数据很多时候跟我们指定的 key 不同，也要循环修改一遍才能用，感觉循环生成Option list是一样的呀，还能保证扩展性

**Comment by afc163** [comment]
👌
