### ISSUE TITLE
【业务组件】FooterToolbar 底部工具栏

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro-site#7]
<img width="1028" alt="2017-07-19 7 53 55" src="https://user-images.githubusercontent.com/7017767/28366238-6f72dffc-6cbe-11e7-8bfe-40533de6381c.png">

[交互稿](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=页底固定工具条)
[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/51658)

**使用方式**

	<FooterToolbar>
		...content...
	</FooterToolbar>

**功能概要**

- 静态容器，相对于页面固定在底部，但宽度与父元素相同

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| style       | 样式   | object     | -    |

**Comment by nikogu** [comment]
感觉这个组件没必要，貌似就是个 `div style=fixed`，不过从场景上讲，我更推荐一个 `<FooterSubmit />` （自带 button，可自定义 icon 的 popover），将长表单滚动 fixed 提交这个模式抽象出来。

**Comment by afc163** [comment]
这种表单校验的形式待商榷。

不过把 Submit Button 加进去确实更到位一些。

**Comment by nikogu** [comment]
如果设计那边能说明这种形式是有效的，提供一种场景组件还是挺实用的，并且体现出了交互思想

**Comment by ddcat1115** [comment]
`div style=fixed` 不能实现这种效果的，它的宽度不是固定的，而是跟着父元素走，样式写起来略麻烦才抽出来的  http://riddle.alibaba-inc.com/riddles/b5dbe897

有几个按钮是不确定的，只能说这种工具条的结构肯定是两列，第一列靠左，第二列靠右，感觉也没有太大必要写进去

补充了交互

**Comment by afc163** [comment]
这种工具条应该只会用于长表单提交，可以类似 Modal 的 footer 给一个默认操作。
