### ISSUE TITLE
Todos about components

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro-site#76]
### 已按照最新视觉比对，有一些组件有模块设计稿，请参考最新 -> [下载源文件 —— 模块-魔鬼终极版](https://lark.alipay.com/ui-assets/leu0s4/assets)

组件名 | 功能/代码 | 样式 | 文档 | demo | 开放 | 反馈
------- | ---- | ------------| --- | --- | ----- | ----
ActiveChart |       |       |   |  | 🚫 仅脚手架内部使用，不具通用性 |
AvatarList |   增加 className 属性，以便定制样式    |   需要根据视觉稿更新，去掉灰色背景    |  ✖️  |  ✖️  | 🚫 目前仅为样式定制，暂不开放 |
Charts |  1. Charts.Gauge 仪表盘刻度能否可配置，目前为写死的『优良中差』；2.  Charts.ChartCard 在 Antd.Card 基础上有定制化的样式，是一个通用需求，并不完全针对内容有 Charts 的场景，感觉应该拆出来再稍微改造，形成模块设计中的 MiniCard     |   Charts.ChartCard，Charts.WaterWave 宽度展示不完全 [ChartCard](https://gw.alipayobjects.com/zos/rmsportal/NBbiToZTMxZXaXsRXkNg.png)   [WaterWave](https://gw.alipayobjects.com/zos/rmsportal/cfOwuYiinhUYeVIfnCRs.png)   | ✔️  | ✔️ | ✔️ |
Countdown |   ✔️    |   ✔️    | ✖️  | ✖️ | ✔️ |
DescriptionList |   ✔️    |   ✔️    | 需要补充响应式相关文档  |  ✔️ | ✔️ |
EditableItem |       |       |   |  | 🚫 |
EditableLinkGroup |       |       |   |  | 🚫  |
Exception | ✔️      |    需要根据视觉高更新   | ✔️  | ✔️ | ✔️ |
FooterToolbar |  ✔️     |    1. 阴影样式不对；2. 左右 padding 应为24px，目前为28px；3. 报错 list 样式需要调整   |  ✖️ | ✖️ | ✔️ |
GlobalFooter |   ✔️    |    ✔️   | ✔️  | ✔️ | ✔️ | 
HeaderSearch |  1. 点击 icon 有报错；2. 点击 icon 再点击其他地方，输入框不会收起；3. 输入框右边也有icon的有效区 [mov](http://p.tb.cn/rmsportal_1055_inputsearch.mov)    |    1. icon 默认应为 16px，且与内容的间距应为 12px    | ✖️   | ✖️   | ✔️ | 
MapChart |  目前为图片占位，后续可实现后放到 Charts 里？     |       |   |  | 🚫 | 
NoticeIcon | NoticeList 是否可用 List 实现？ | 1. 列表边距不对；2. 待办列表中的tag样式不对；3. icon 默认应为 16px      | ✔️   | ✔️ | ✔️ |
PageHeader |   ✔️     |   边距等需要按照最新视觉稿更新    |  需要增加响应式有关的说明  | ✔️  | ✔️  |
Result |  ✔️     |   需要按照最新视觉稿更新    | ✔️  | ✔️ | ✔️ |
SearchInput |   增加 className 属性，以便定制样式   |   ✔️    |  ✖️  |  ✖️  |  ✔️ |
StandardFormRow |       |       |   |  | 🚫 |
StandardTable |       |       |   |  | 🚫 |
TagCloud |  挪到 Charts 里？     |   ✔️    |  ✖️ | ✖️ | ✔️ |
TagSelect |  增加 className 属性，以便定制样式     |   ✔️    | ✖️  | ✖️ |  ✔️ |
TimelineChart |  迁移到 Charts 里？     |   ✔️    |  ✖️ |  ✖️ |  ✔️ |

**Comment by afc163** [comment]
StandardFormRow、StandardTable、EditableLinkGroup 这种就没必要了。加一列不开放。

**Comment by afc163** [comment]
SearchInput 用 http://beta.ant.design/components/input/#components-input-demo-search-input 重构。

**Comment by afc163** [comment]
- [ ] NoticeIcon
- [ ] HeaderSearch
- [ ] FooterToolbar
- [ ] GlobalFooter

**Comment by nikogu** [comment]
- [x] Charts
  - [ ] TagCloud 放入 Charts 中
  - [ ] TimelineChart 放入 Charts 中
  - [x] Charts.Trend 响应式问题（ChartCard 宽度展示不完全）
  - [x] Charts.WaterWave 宽度展示不完全
  - [x] Charts.Gauge 自定义刻度 labels
  - <del>Charts.ChartCard 抽离通用</del> 场景较为固定，跟设计图表的配合紧密，很难有其他场景单独使用，建议抽离

- [x] Countdown 文档+DEMO

- [ ] MapChart 去除

- [ ] SearchInput 使用 antd 新 input

- [ ] TagSelect 添加 className

**Comment by afc163** [comment]
Countdown => CountDown

**Comment by ddcat1115** [comment]
- DescriptionList
	- [ ] 需要补充响应式相关文档
- Exception
	- [ ] 需要根据视觉稿更新
- PageHeader
	- [ ] 需要根据视觉稿更新
	- [ ] 需要补充响应式相关说明
- Result
	- [ ] 需要根据视觉稿更新

**Comment by ddcat1115** [comment]
### 目前一共开放 11 个组件

- Charts 图标 （集合）
- CountDown 倒计时
- DescriptionList 描述列表
- Exception 异常
- FooterToolbar 底部固定工具栏
- GlobalFooter 全局页脚
- HeaderSearch 全局搜索
- NoticeIcon 通知菜单
- PageHeader 页头
- Result 处理结果
- TagSelect 标签选择器
