### ISSUE TITLE
站点开发

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-site#77]
- [x] 页头页尾功能：@nikogu
    - [x] 全局头部
    - [x] 搜索功能（搜索内容后期可持续优化） https://github.com/ant-design/ant-design/issues/7436
    - [x] 全局底部
    - [x] 底部内容信息
- [x] 组件和文档内容区：@ddcat1115
- [ ] 首页：@afc163

**Comment by nikogu** [comment]
@afc163 听说你在忙着二次 review 的修复，要不首页我来搞？

**Comment by afc163** [comment]
首页罗宪在搞。

**Comment by nikogu** [comment]
好的... 💯
