### ISSUE TITLE
组件 demo 样式同步

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-site#81]
目前样式还没和模板同步。

**Comment by nikogu** [comment]
https://ant-design.github.io/test/components/Charts

**Comment by afc163** [comment]
https://github.com/ant-design/test2/blob/1e54651cd46a3fdb2e266851c6ba347d4aadf1b4/.roadhogrc#L8

**Comment by nikogu** [comment]
fixed

**Comment by afc163** [comment]
我这个是指 demo 要同步，因为设计稿变化，demo 没跟上。
