### ISSUE TITLE
需要一个发布流程

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-site#87]

**Comment by nikogu** [comment]
- [ ] 发布流程说明
- [ ] 自动版本号

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro-site/wiki/Ant-Design-Pro-%E5%8F%91%E5%B8%83%E6%B5%81%E7%A8%8B

**Comment by afc163** [comment]
有几点要明确一下：

- 怎么写 changelog，怎么对比 commits。
- 是否要发 release。

**Comment by nikogu** [comment]
update 了 @ddcat1115 一起来看看是否清晰明确

**Comment by ddcat1115** [comment]
感觉挺清楚的，后面每个人都可以发下，过程中再看看有啥要补充的没

**Comment by afc163** [comment]
👍
