### ISSUE TITLE
优化搜索样式

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro-site#88]
- [x] 需要有一个 loading 效果
- [ ] 关键词没匹配结果要有『没有找到』。

**Comment by nikogu** [comment]
> loading 效果，这个好像被雷锋同学加了

**Comment by afc163** [comment]
效果不好，最好加到浮层里。

**Comment by nikogu** [comment]
> 关键词没匹配结果要有『没有找到』

这个感觉没必要..＝。-
