### ISSUE TITLE
首页响应式问题

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-pro-site#91]
![image](https://user-images.githubusercontent.com/1179603/32213212-5b883bf6-bde8-11e7-9adf-72e0078a683e.png)
`800 x Any 左右` 

![image](https://user-images.githubusercontent.com/1179603/32213223-655f5aba-bde8-11e7-8f7e-20211191062e.png)
`560 x Any 左右`

还是有点细节问题 ＝。-

**Comment by jljsj33** [comment]
不管。。。强制缩窗口一律不管

**Comment by nikogu** [comment]
哦＝。-
