### ISSUE TITLE
打包优化

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-pro-site#99]
- [ ] 支持变量覆盖，提供 ant-design-pro/dist/ant-design-pro.less
- [ ] 引入样式的更优选择，提供类似 babel 的转换 css module 的 less/css 工具

**Comment by chenshuai2144** [comment]
>  引入样式的更优选择，提供类似 babel 的转换 css module 的 less/css 工具 

这句话是什么意思？

**Comment by nikogu** [comment]
@chenshuai2144 现在 pro 组件的引入，是直接引入 css 样式吧，期望是像 antd 一样？按需加载对应的 css？之前要搞 less 是为了换主题，不过你这个不是上次搞了吗

**Comment by chenshuai2144** [comment]
搞了 但是并不支持babel import。
几乎是要重写整个脚手架了。 pro 情况特殊

**Comment by nikogu** [comment]
@chenshuai2144 跟脚手架无关，不用重写啊，看下 https://github.com/ant-design/babel-plugin-import 源码呢

**Comment by yesmeck** [comment]
组件要构建出跟 antd 组件一样的 style 结构 https://unpkg.com/antd@3.4.0/lib/button/style/

构建出来的组件代码里不能 import 样式。

**Comment by chenshuai2144** [comment]
改起来比重写都难

**Comment by afc163** [comment]
pro 不需要支持 babel-plugin-import

**Comment by chenshuai2144** [comment]
话题终结

**Comment by yesmeck** [comment]
现在构建出来的 lib 是有问题的，组建里 import 了 antd 的 css 导致项目不能用 antd 的 less
样式(样式会加载两次且不能修改主题)

**Comment by chenshuai2144** [comment]
现在提供了一个可以全部导入的 less

**Comment by yesmeck** [comment]
全部导入的 less 不能解决样式加载两次的问题。
